
all: 		
	gcc -g -Wall -o s-talk -pthread listMonitor.c main.c list.c
#	gcc -g -Wall -o testMonitor -pthread listMonitor.c listMonitorTest.c list.c 
# 			^^ Uncomment to test listMonitor ^^ 
clean:
	rm s-talk
#	rm testMonitor